### ISSUE TITLE
while building nvdsinfer_custom_impl_Yolo though make command , i get below error . Kindly assist

### ISSUE THREAD

**Issue by h9945394143** [Tianxiaomo/pytorch-YOLOv4#541]
root@39026ff1831b:/app/sriharsha/pytorch-YOLOv4/DeepStream/nvdsinfer_custom_impl_Yolo# make
g++ -c -o nvdsinfer_yolo_engine.o -Wall -std=c++11 -shared -fPIC -Wno-error=deprecated-declarations -I/opt/nvidia/deepstream/deepstream-6.1/sources/includes -I/usr/local/cuda-11.6/include nvdsinfer_yolo_engine.cpp
In file included from nvdsinfer_yolo_engine.cpp:25:
yoloPlugins.h: In member function 'virtual nvinfer1::IPluginV2* YoloLayerV3PluginCreator::deserializePlugin(const char*, const void*, size_t)':
**yoloPlugins.h:122:56: error: invalid new-expression of abstract class type 'YoloLayerV3'
  122 |         return new YoloLayerV3(serialData, serialLength) ;**
      |                                                        ^
yoloPlugins.h:50:7: note:   because the following virtual functions are pure within 'YoloLayerV3':
   50 | class YoloLayerV3 : public nvinfer1::IPluginV2
      |       ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/NvInferLegacyDims.h:53,
                 from /usr/include/x86_64-linux-gnu/NvInfer.h:53,
                 from /usr/include/x86_64-linux-gnu/NvCaffeParser.h:53,
                 from /opt/nvidia/deepstream/deepstream-6.1/sources/includes/nvdsinfer_custom_impl.h:126,
                 from nvdsinfer_yolo_engine.cpp:23:
/usr/include/x86_64-linux-gnu/NvInferRuntimeCommon.h:606:21: note:      'virtual int32_t nvinfer1::IPluginV2::enqueue(int32_t, const void* const*, void* const*, void*, cudaStream_t)'
  606 |     virtual int32_t enqueue(int32_t batchSize, void const* const* inputs, void* const* outputs, void* workspace,
      |                     ^~~~~~~
make: *** [Makefile:51: nvdsinfer_yolo_engine.o] Error 1
root@39026ff1831b:/app/sriharsha/pytorch-YOLOv4/DeepStream/nvdsinfer_custom_impl_Yolo#

**Comment by PhiDCH** [comment]
i have the same error when compile with cuda 11.7 in DeepStream 6.1
